[2024-10-03T21:35:26.562-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-03T21:35:28.692-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: huggingface_pdf_pipeline.upload_pdfs_task manual__2024-10-04T01:33:18.344581+00:00 [queued]>
[2024-10-03T21:35:28.879-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: huggingface_pdf_pipeline.upload_pdfs_task manual__2024-10-04T01:33:18.344581+00:00 [queued]>
[2024-10-03T21:35:28.882-0400] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-03T21:35:29.054-0400] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): upload_pdfs_task> on 2024-10-04 01:33:18.344581+00:00
[2024-10-03T21:35:29.059-0400] {standard_task_runner.py:72} INFO - Started process 14396 to run task
[2024-10-03T21:35:29.061-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'huggingface_pdf_pipeline', 'upload_pdfs_task', 'manual__2024-10-04T01:33:18.344581+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/huggingface_pdf_airflow_dag.py', '--cfg-path', '/tmp/tmpktn564zl']
[2024-10-03T21:35:29.062-0400] {standard_task_runner.py:105} INFO - Job 22: Subtask upload_pdfs_task
[2024-10-03T21:35:40.323-0400] {job.py:229} INFO - Heartbeat recovered after 35.88 seconds
[2024-10-03T21:35:46.772-0400] {task_command.py:467} INFO - Running <TaskInstance: huggingface_pdf_pipeline.upload_pdfs_task manual__2024-10-04T01:33:18.344581+00:00 [running]> on host LAPTOP-GD5THE3N.
[2024-10-03T21:35:58.014-0400] {job.py:229} INFO - Heartbeat recovered after 17.79 seconds
[2024-10-03T21:36:12.285-0400] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='huggingface_pdf_pipeline' AIRFLOW_CTX_TASK_ID='upload_pdfs_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T01:33:18.344581+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T01:33:18.344581+00:00'
[2024-10-03T21:36:12.287-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-03T21:36:12.288-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-03T21:36:12.289-0400] {logging_mixin.py:190} INFO - Current task name:upload_pdfs_task state:running start_date:2024-10-04 01:35:28.694504+00:00
[2024-10-03T21:36:12.290-0400] {logging_mixin.py:190} INFO - Dag name:huggingface_pdf_pipeline and current dag run status:running
[2024-10-03T21:36:12.291-0400] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-03T21:36:12.292-0400] {logging_mixin.py:190} INFO - Error uploading / to Azure Blob Storage Container 1: Please specify a container name and blob name.
[2024-10-03T21:36:12.293-0400] {logging_mixin.py:190} INFO - Error uploading h to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'h'
[2024-10-03T21:36:12.297-0400] {logging_mixin.py:190} INFO - Error uploading o to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'o'
[2024-10-03T21:36:12.299-0400] {logging_mixin.py:190} INFO - Error uploading m to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'm'
[2024-10-03T21:36:12.300-0400] {logging_mixin.py:190} INFO - Error uploading e to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'e'
[2024-10-03T21:36:12.301-0400] {logging_mixin.py:190} INFO - Error uploading / to Azure Blob Storage Container 1: Please specify a container name and blob name.
[2024-10-03T21:36:12.302-0400] {logging_mixin.py:190} INFO - Error uploading p to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'p'
[2024-10-03T21:36:12.303-0400] {logging_mixin.py:190} INFO - Error uploading a to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'a'
[2024-10-03T21:36:12.303-0400] {logging_mixin.py:190} INFO - Error uploading t to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 't'
[2024-10-03T21:36:12.304-0400] {logging_mixin.py:190} INFO - Error uploading r to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'r'
[2024-10-03T21:36:12.305-0400] {logging_mixin.py:190} INFO - Error uploading i to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'i'
[2024-10-03T21:36:12.306-0400] {logging_mixin.py:190} INFO - Error uploading c to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'c'
[2024-10-03T21:36:12.306-0400] {logging_mixin.py:190} INFO - Error uploading k to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'k'
[2024-10-03T21:36:12.307-0400] {logging_mixin.py:190} INFO - Error uploading / to Azure Blob Storage Container 1: Please specify a container name and blob name.
[2024-10-03T21:36:12.307-0400] {logging_mixin.py:190} INFO - Error uploading D to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'D'
[2024-10-03T21:36:12.308-0400] {logging_mixin.py:190} INFO - Error uploading o to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'o'
[2024-10-03T21:36:12.309-0400] {logging_mixin.py:190} INFO - Error uploading w to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'w'
[2024-10-03T21:36:12.309-0400] {logging_mixin.py:190} INFO - Error uploading n to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'n'
[2024-10-03T21:36:12.311-0400] {logging_mixin.py:190} INFO - Error uploading l to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'l'
[2024-10-03T21:36:12.311-0400] {logging_mixin.py:190} INFO - Error uploading o to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'o'
[2024-10-03T21:36:12.312-0400] {logging_mixin.py:190} INFO - Error uploading a to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'a'
[2024-10-03T21:36:12.313-0400] {logging_mixin.py:190} INFO - Error uploading d to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'd'
[2024-10-03T21:36:12.313-0400] {logging_mixin.py:190} INFO - Error uploading s to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 's'
[2024-10-03T21:36:12.314-0400] {python.py:240} INFO - Done. Returned value was: None
[2024-10-03T21:36:24.270-0400] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-03T21:36:24.273-0400] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=huggingface_pdf_pipeline, task_id=upload_pdfs_task, run_id=manual__2024-10-04T01:33:18.344581+00:00, execution_date=20241004T013318, start_date=20241004T013528, end_date=20241004T013624
[2024-10-03T21:36:25.195-0400] {logging_mixin.py:190} INFO - Task instance in success state
[2024-10-03T21:36:25.200-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-10-03T21:36:25.202-0400] {logging_mixin.py:190} INFO - Dag name:huggingface_pdf_pipeline queued_at:2024-10-04 01:33:18.948932+00:00
[2024-10-03T21:36:25.203-0400] {logging_mixin.py:190} INFO - Task hostname:LAPTOP-GD5THE3N. operator:PythonOperator
[2024-10-03T21:36:26.994-0400] {job.py:229} INFO - Heartbeat recovered after 29.07 seconds
[2024-10-03T21:36:34.218-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-03T21:36:39.135-0400] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-10-03T21:36:44.385-0400] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-03T21:36:44.511-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
