[2024-10-03T22:45:45.679-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-03T22:45:47.481-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: huggingface_pdf_pipeline.upload_pdfs_task manual__2024-10-04T02:39:31.050432+00:00 [None]>
[2024-10-03T22:45:47.656-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: huggingface_pdf_pipeline.upload_pdfs_task manual__2024-10-04T02:39:31.050432+00:00 [None]>
[2024-10-03T22:45:47.660-0400] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2024-10-03T22:45:47.882-0400] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): upload_pdfs_task> on 2024-10-04 02:39:31.050432+00:00
[2024-10-03T22:45:47.889-0400] {standard_task_runner.py:72} INFO - Started process 33228 to run task
[2024-10-03T22:45:47.892-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'huggingface_pdf_pipeline', 'upload_pdfs_task', 'manual__2024-10-04T02:39:31.050432+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/huggingface_pdf_airflow_dag.py', '--cfg-path', '/tmp/tmpezsq071p']
[2024-10-03T22:45:47.894-0400] {standard_task_runner.py:105} INFO - Job 41: Subtask upload_pdfs_task
[2024-10-03T22:45:58.657-0400] {job.py:229} INFO - Heartbeat recovered after 22.28 seconds
[2024-10-03T22:46:06.299-0400] {task_command.py:467} INFO - Running <TaskInstance: huggingface_pdf_pipeline.upload_pdfs_task manual__2024-10-04T02:39:31.050432+00:00 [running]> on host LAPTOP-GD5THE3N.
[2024-10-03T22:46:31.648-0400] {job.py:229} INFO - Heartbeat recovered after 33.12 seconds
[2024-10-03T22:46:42.289-0400] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='huggingface_pdf_pipeline' AIRFLOW_CTX_TASK_ID='upload_pdfs_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T02:39:31.050432+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T02:39:31.050432+00:00'
[2024-10-03T22:46:42.292-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-03T22:46:42.293-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-03T22:46:42.293-0400] {logging_mixin.py:190} INFO - Current task name:upload_pdfs_task state:running start_date:2024-10-04 02:45:47.483605+00:00
[2024-10-03T22:46:42.294-0400] {logging_mixin.py:190} INFO - Dag name:huggingface_pdf_pipeline and current dag run status:running
[2024-10-03T22:46:42.295-0400] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-03T22:46:42.296-0400] {logging_mixin.py:190} INFO - Error uploading / to Azure Blob Storage Container 1: Please specify a container name and blob name.
[2024-10-03T22:46:42.298-0400] {logging_mixin.py:190} INFO - Error uploading h to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'h'
[2024-10-03T22:46:42.299-0400] {logging_mixin.py:190} INFO - Error uploading o to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'o'
[2024-10-03T22:46:42.300-0400] {logging_mixin.py:190} INFO - Error uploading m to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'm'
[2024-10-03T22:46:42.300-0400] {logging_mixin.py:190} INFO - Error uploading e to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'e'
[2024-10-03T22:46:42.301-0400] {logging_mixin.py:190} INFO - Error uploading / to Azure Blob Storage Container 1: Please specify a container name and blob name.
[2024-10-03T22:46:42.301-0400] {logging_mixin.py:190} INFO - Error uploading p to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'p'
[2024-10-03T22:46:42.302-0400] {logging_mixin.py:190} INFO - Error uploading a to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'a'
[2024-10-03T22:46:42.303-0400] {logging_mixin.py:190} INFO - Error uploading t to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 't'
[2024-10-03T22:46:42.303-0400] {logging_mixin.py:190} INFO - Error uploading r to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'r'
[2024-10-03T22:46:42.304-0400] {logging_mixin.py:190} INFO - Error uploading i to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'i'
[2024-10-03T22:46:42.305-0400] {logging_mixin.py:190} INFO - Error uploading c to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'c'
[2024-10-03T22:46:42.305-0400] {logging_mixin.py:190} INFO - Error uploading k to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'k'
[2024-10-03T22:46:42.306-0400] {logging_mixin.py:190} INFO - Error uploading / to Azure Blob Storage Container 1: Please specify a container name and blob name.
[2024-10-03T22:46:42.307-0400] {logging_mixin.py:190} INFO - Error uploading D to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'D'
[2024-10-03T22:46:42.308-0400] {logging_mixin.py:190} INFO - Error uploading o to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'o'
[2024-10-03T22:46:42.308-0400] {logging_mixin.py:190} INFO - Error uploading w to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'w'
[2024-10-03T22:46:42.309-0400] {logging_mixin.py:190} INFO - Error uploading n to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'n'
[2024-10-03T22:46:42.309-0400] {logging_mixin.py:190} INFO - Error uploading l to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'l'
[2024-10-03T22:46:42.311-0400] {logging_mixin.py:190} INFO - Error uploading o to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'o'
[2024-10-03T22:46:42.312-0400] {logging_mixin.py:190} INFO - Error uploading a to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'a'
[2024-10-03T22:46:42.312-0400] {logging_mixin.py:190} INFO - Error uploading d to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 'd'
[2024-10-03T22:46:42.313-0400] {logging_mixin.py:190} INFO - Error uploading s to Azure Blob Storage Container 1: [Errno 2] No such file or directory: 's'
[2024-10-03T22:46:42.313-0400] {python.py:240} INFO - Done. Returned value was: None
[2024-10-03T22:46:45.139-0400] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-03T22:46:45.141-0400] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=huggingface_pdf_pipeline, task_id=upload_pdfs_task, run_id=manual__2024-10-04T02:39:31.050432+00:00, execution_date=20241004T023931, start_date=20241004T024547, end_date=20241004T024645
[2024-10-03T22:46:45.429-0400] {logging_mixin.py:190} INFO - Task instance in success state
[2024-10-03T22:46:45.431-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-10-03T22:46:45.433-0400] {logging_mixin.py:190} INFO - Dag name:huggingface_pdf_pipeline queued_at:2024-10-04 02:39:31.827011+00:00
[2024-10-03T22:46:45.434-0400] {logging_mixin.py:190} INFO - Task hostname:LAPTOP-GD5THE3N. operator:PythonOperator
[2024-10-03T22:46:47.650-0400] {job.py:229} INFO - Heartbeat recovered after 16.22 seconds
[2024-10-03T22:46:48.740-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-03T22:46:52.750-0400] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-03T22:46:52.799-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-03T22:46:52.964-0400] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
