[2024-10-05T13:39:04.598-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-05T13:39:14.159-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: huggingface_pdf_pipeline.extract_texts_task scheduled__2024-10-04T00:00:00+00:00 [queued]>
[2024-10-05T13:39:14.327-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: huggingface_pdf_pipeline.extract_texts_task scheduled__2024-10-04T00:00:00+00:00 [queued]>
[2024-10-05T13:39:14.329-0400] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-05T13:39:14.532-0400] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_texts_task> on 2024-10-04 00:00:00+00:00
[2024-10-05T13:39:14.537-0400] {standard_task_runner.py:72} INFO - Started process 3943 to run task
[2024-10-05T13:39:14.539-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'huggingface_pdf_pipeline', 'extract_texts_task', 'scheduled__2024-10-04T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/huggingface_pdf_airflow_dag.py', '--cfg-path', '/tmp/tmpjl168kfy']
[2024-10-05T13:39:14.540-0400] {standard_task_runner.py:105} INFO - Job 60: Subtask extract_texts_task
[2024-10-05T13:39:24.663-0400] {job.py:229} INFO - Heartbeat recovered after 33.89 seconds
[2024-10-05T13:39:25.003-0400] {task_command.py:467} INFO - Running <TaskInstance: huggingface_pdf_pipeline.extract_texts_task scheduled__2024-10-04T00:00:00+00:00 [running]> on host LAPTOP-GD5THE3N.
[2024-10-05T13:39:38.555-0400] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='huggingface_pdf_pipeline' AIRFLOW_CTX_TASK_ID='extract_texts_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-04T00:00:00+00:00'
[2024-10-05T13:39:38.556-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-05T13:39:38.557-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-05T13:39:38.557-0400] {logging_mixin.py:190} INFO - Current task name:extract_texts_task state:running start_date:2024-10-05 17:39:14.161323+00:00
[2024-10-05T13:39:38.558-0400] {logging_mixin.py:190} INFO - Dag name:huggingface_pdf_pipeline and current dag run status:running
[2024-10-05T13:39:38.558-0400] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-05T13:39:38.561-0400] {logging_mixin.py:190} INFO - Error extracting text from /: [Errno 21] Is a directory: '/'
[2024-10-05T13:39:38.562-0400] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/User/Documents/GitHub/DAMG7245/big_data_assignment2/airflow/dags/modules/pipeline.py", line 191, in extract_texts_from_pdfs
    file_size_mb = os.path.getsize(pdf_path) / (1024 * 1024)
  File "/usr/lib/python3.10/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'h'
[2024-10-05T13:39:40.860-0400] {job.py:229} INFO - Heartbeat recovered after 16.32 seconds
[2024-10-05T13:39:41.311-0400] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-05T13:39:41.314-0400] {logging_mixin.py:190} INFO - Task start:2024-10-05 17:39:14.161323+00:00 end:2024-10-05 17:39:41.311205+00:00 duration:27.149882
[2024-10-05T13:39:41.316-0400] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_texts_task> dag:<DAG: huggingface_pdf_pipeline> dagrun:<DagRun huggingface_pdf_pipeline @ 2024-10-04 00:00:00+00:00: scheduled__2024-10-04T00:00:00+00:00, state:running, queued_at: 2024-10-05 17:27:34.552395+00:00. externally triggered: False>
[2024-10-05T13:39:41.317-0400] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: 'h'
[2024-10-05T13:39:41.319-0400] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=huggingface_pdf_pipeline, task_id=extract_texts_task, run_id=scheduled__2024-10-04T00:00:00+00:00, execution_date=20241004T000000, start_date=20241005T173914, end_date=20241005T173941
[2024-10-05T13:39:41.551-0400] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-05T13:39:41.553-0400] {standard_task_runner.py:124} ERROR - Failed to execute job 60 for task extract_texts_task ([Errno 2] No such file or directory: 'h'; 3943)
Traceback (most recent call last):
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/patrick/.cache/pypoetry/virtualenvs/airflow-wPbgcfzP-py3.10/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/User/Documents/GitHub/DAMG7245/big_data_assignment2/airflow/dags/modules/pipeline.py", line 191, in extract_texts_from_pdfs
    file_size_mb = os.path.getsize(pdf_path) / (1024 * 1024)
  File "/usr/lib/python3.10/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'h'
[2024-10-05T13:39:45.684-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-05T13:39:48.616-0400] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-05T13:39:48.721-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-05T13:39:49.578-0400] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
